@startuml
 class Car {
  + Brand : String
  + Name : String
  + Category : String
  + Fuel Type : String
  + Image : String
  + State : String
  + City : String
  + Area : String
  + Price : Double
  + Description ：String
  + Status : int
  + CreateTime : Bigint
  + EditTime : Bigint
  - Read Car()
  - Add Car()
  - Update Car()
  - Delete Car()
 }

 class Order{

 }

 class Customer {
  + Username : String
  + Password : String
  + Name : String
  + City : String
  + Address : String
  + Mobile : String
  + Email : String
  + Gender : String
  + BOD : Date
  - updateProfile()
  - bookCar()
  - buyCar()
  - giveFeedback()
 }

 class Seller{
    + Username : String
    + Password : String
    + Name : String
    + City : String
    + Address : String
    + Mobile : String
    + Email : String
    + Gender : String
    + BOD : Date
    - updateProfile()
    - sellCar()
    - giveFeedback()
 }

 class Admin{
     + Username : String
     + Password : String
     - viewFeedback()
     - manageUser()
 }

@enduml